// Short German exchanges (A1–A2) for a parent at a German primary school.
// Each dialog is one question and one answer. `who`: me (the parent practising), teacher, parent, kid.
const SPEAKERS = { me: '你', teacher: '老師', parent: '其他家長', kid: '小朋友' };
const SCENES = { teacher: '跟老師', parent: '跟其他家長', kid: '跟其他小朋友' };

const DIALOGS = [
  // ---------------------------------------------------------------- 跟老師（Sie）
  ['teacher', 'me', 'Guten Morgen! Chris ist mein Sohn.', '早安！Chris 是我兒子。',
   'teacher', 'Schön, Sie kennenzulernen. Chris ist in meiner Klasse.', '很高興認識您。Chris 在我班上。'],
  ['teacher', 'me', 'Wie macht sich Chris in der Schule?', 'Chris 在學校表現怎麼樣？',
   'teacher', 'Er macht das sehr gut. Er ist fleißig und freundlich.', '他表現得很好，很認真也很友善。'],
  ['teacher', 'me', 'Chris ist heute krank. Er kann nicht zur Schule kommen.', 'Chris 今天生病了，不能來上學。',
   'teacher', 'Gute Besserung! Danke für die Nachricht.', '祝他早日康復！謝謝您通知。'],
  ['teacher', 'teacher', 'Hat Chris seine Hausaufgaben gemacht?', 'Chris 寫功課了嗎？',
   'me', 'Ja, er hat sie gestern gemacht.', '有，他昨天寫好了。'],
  ['teacher', 'me', 'Was braucht Chris für morgen?', 'Chris 明天需要帶什麼？',
   'teacher', 'Er braucht seine Sportsachen und eine Trinkflasche.', '他需要帶運動用品和水壺。'],
  ['teacher', 'me', 'Wann ist der Elternabend?', '家長會是什麼時候？',
   'teacher', 'Der Elternabend ist am Dienstag um 19 Uhr.', '家長會在星期二晚上 7 點。'],
  ['teacher', 'me', 'Darf ich Sie etwas fragen?', '我可以問您一件事嗎？',
   'teacher', 'Ja, natürlich. Was möchten Sie wissen?', '當然可以。您想知道什麼？'],
  ['teacher', 'me', 'Chris spricht noch nicht so gut Deutsch.', 'Chris 的德文還說得不太好。',
   'teacher', 'Kein Problem. Er lernt jeden Tag dazu.', '沒關係，他每天都在進步。'],
  ['teacher', 'me', 'Wie kann ich Chris zu Hause helfen?', '我在家可以怎麼幫 Chris？',
   'teacher', 'Lesen Sie jeden Tag zehn Minuten mit ihm.', '請每天陪他讀十分鐘。'],
  ['teacher', 'teacher', 'Können Sie bitte das Formular unterschreiben?', '可以請您在這張表格上簽名嗎？',
   'me', 'Ja, ich bringe es morgen mit.', '好，我明天帶來。'],
  ['teacher', 'me', 'Ich hole Chris heute früher ab, um 11 Uhr.', '我今天會早點接 Chris，11 點。',
   'teacher', 'In Ordnung, danke für die Information.', '好的，謝謝您告訴我。'],
  ['teacher', 'me', 'Wann ist heute Schulschluss?', '今天幾點放學？',
   'teacher', 'Heute ist um 12 Uhr Schluss.', '今天 12 點放學。'],
  ['teacher', 'teacher', 'Chris hat heute seine Postmappe vergessen.', 'Chris 今天忘了帶聯絡夾。',
   'me', 'Oh, Entschuldigung. Ich denke morgen daran.', '喔，抱歉。我明天會記得。'],
  ['teacher', 'me', 'Hat Chris Freunde in der Klasse?', 'Chris 在班上有朋友嗎？',
   'teacher', 'Ja, er spielt oft mit Max und Ali.', '有，他常常跟 Max 和 Ali 一起玩。'],
  ['teacher', 'me', 'Wie viel kostet der Ausflug?', '校外教學要多少錢？',
   'teacher', 'Der Ausflug kostet acht Euro.', '校外教學要 8 歐元。'],
  ['teacher', 'me', 'Wohin geht der Ausflug?', '校外教學要去哪裡？',
   'teacher', 'Wir fahren in den Zoo.', '我們要去動物園。'],
  ['teacher', 'teacher', 'Hat Chris eine Allergie?', 'Chris 有過敏嗎？',
   'me', 'Nein, er hat keine Allergien.', '沒有，他沒有過敏。'],
  ['teacher', 'me', 'Chris hat heute ein bisschen Bauchweh.', 'Chris 今天肚子有點痛。',
   'teacher', 'Danke, ich passe gut auf ihn auf.', '謝謝，我會好好注意他。'],
  ['teacher', 'me', 'Können wir einen Termin machen?', '我們可以約個時間談嗎？',
   'teacher', 'Gern. Wann haben Sie Zeit?', '好啊。您什麼時候有空？'],
  ['teacher', 'teacher', 'Passt Ihnen Donnerstag um 14 Uhr?', '星期四下午 2 點您方便嗎？',
   'me', 'Ja, das passt mir gut.', '好，這個時間我可以。'],
  ['teacher', 'teacher', 'Chris war heute sehr müde.', 'Chris 今天很累。',
   'me', 'Er ist gestern spät ins Bett gegangen. Das tut mir leid.', '他昨天很晚才睡，不好意思。'],
  ['teacher', 'me', 'Was lernen die Kinder gerade in Mathe?', '孩子們現在數學在學什麼？',
   'teacher', 'Wir üben gerade Plus und Minus.', '我們現在在練習加法和減法。'],
  ['teacher', 'me', 'Hat die Klasse morgen Sport?', '班上明天有體育課嗎？',
   'teacher', 'Ja, morgen ist Sport in der Turnhalle.', '有，明天在體育館上體育課。'],
  ['teacher', 'me', 'Muss Chris Hausschuhe mitbringen?', 'Chris 需要帶室內拖鞋嗎？',
   'teacher', 'Ja, bitte. Die Kinder tragen in der Klasse Hausschuhe.', '要，麻煩了。孩子們在教室裡穿室內拖鞋。'],
  ['teacher', 'teacher', 'Wer holt Chris heute ab?', '今天誰來接 Chris？',
   'me', 'Heute holt ihn seine Oma ab.', '今天他奶奶（外婆）來接他。'],
  ['teacher', 'me', 'Ich verstehe den Brief nicht ganz.', '這封信我看不太懂。',
   'teacher', 'Kein Problem, ich erkläre es Ihnen.', '沒關係，我解釋給您聽。'],
  ['teacher', 'me', 'Können Sie bitte langsamer sprechen?', '可以請您說慢一點嗎？',
   'teacher', 'Ja, natürlich. Entschuldigung.', '當然，抱歉。'],
  ['teacher', 'me', 'Wo finde ich den Stundenplan?', '課表在哪裡可以看到？',
   'teacher', 'Der Stundenplan ist in der Postmappe.', '課表在聯絡夾裡。'],
  ['teacher', 'me', 'Vielen Dank für Ihre Hilfe!', '非常謝謝您的幫忙！',
   'teacher', 'Gern geschehen. Einen schönen Tag noch!', '不客氣，祝您有美好的一天！'],
  ['teacher', 'me', 'Auf Wiedersehen, bis morgen!', '再見，明天見！',
   'teacher', 'Auf Wiedersehen! Tschüss, Chris!', '再見！Chris 掰掰！'],

  // ---------------------------------------------------------------- 跟其他家長（Sie）
  ['parent', 'me', 'Ist Ihr Kind auch in der ersten Klasse?', '您的孩子也是一年級嗎？',
   'parent', 'Ja, meine Tochter geht in die 1b.', '是的，我女兒在 1b 班。'],
  ['parent', 'parent', 'Wie heißt Ihr Kind?', '您的孩子叫什麼名字？',
   'me', 'Mein Sohn heißt Chris.', '我兒子叫 Chris。'],
  ['parent', 'parent', 'Woher kommen Sie?', '您是從哪裡來的？',
   'me', 'Ich komme aus Taiwan.', '我來自台灣。'],
  ['parent', 'parent', 'Wie lange wohnen Sie schon hier?', '您在這裡住多久了？',
   'me', 'Wir wohnen seit einem Jahr hier.', '我們在這裡住了一年。'],
  ['parent', 'me', 'Wo wohnen Sie?', '您住在哪裡？',
   'parent', 'Wir wohnen gleich hier um die Ecke.', '我們就住在轉角那邊。'],
  ['parent', 'me', 'Sprechen Sie Englisch?', '您會說英文嗎？',
   'parent', 'Ja, ein bisschen.', '會，一點點。'],
  ['parent', 'parent', 'Sprechen Sie Deutsch?', '您會說德文嗎？',
   'me', 'Ein bisschen. Ich lerne noch.', '一點點，我還在學。'],
  ['parent', 'me', 'Wissen Sie, wann der Elternabend ist?', '您知道家長會是什麼時候嗎？',
   'parent', 'Ich glaube, am Dienstag um 19 Uhr.', '我想是星期二晚上 7 點。'],
  ['parent', 'me', 'Haben Sie den Brief von der Lehrerin bekommen?', '您有收到老師的信嗎？',
   'parent', 'Ja, es geht um den Ausflug.', '有，是關於校外教學的。'],
  ['parent', 'parent', 'Möchte Chris am Samstag zu uns zum Spielen kommen?', 'Chris 星期六想來我們家玩嗎？',
   'me', 'Ja, gern! Um wie viel Uhr?', '好啊！幾點呢？'],
  ['parent', 'me', 'Wann soll ich Chris wieder abholen?', '我什麼時候來接 Chris 回家？',
   'parent', 'Um 17 Uhr, wenn das passt.', '下午 5 點，如果您方便的話。'],
  ['parent', 'me', 'Kann ich Ihre Telefonnummer haben?', '可以給我您的電話號碼嗎？',
   'parent', 'Ja, gern. Ich schreibe sie Ihnen auf.', '好啊，我寫給您。'],
  ['parent', 'parent', 'Sind Sie auch in der WhatsApp-Gruppe der Klasse?', '您也在班上的 WhatsApp 群組裡嗎？',
   'me', 'Nein, noch nicht. Können Sie mich hinzufügen?', '還沒有。可以請您把我加進去嗎？'],
  ['parent', 'me', 'Wann hat Ihre Tochter Geburtstag?', '您女兒什麼時候生日？',
   'parent', 'Nächsten Freitag. Chris ist herzlich eingeladen!', '下星期五。誠摯邀請 Chris 來參加！'],
  ['parent', 'me', 'Was wünscht sich Ihre Tochter zum Geburtstag?', '您女兒生日想要什麼禮物？',
   'parent', 'Sie mag Bücher und Bastelsachen.', '她喜歡書和美勞用品。'],
  ['parent', 'parent', 'Isst Chris alles?', 'Chris 什麼都吃嗎？',
   'me', 'Fast alles. Nur nichts Scharfes.', '幾乎都吃，只是不吃辣的。'],
  ['parent', 'me', 'Bastelt Ihr Kind auch eine Laterne?', '您的孩子也在做燈籠嗎？',
   'parent', 'Ja, für den Laternenumzug im November.', '是的，為了十一月的提燈遊行。'],
  ['parent', 'me', 'Wo kaufen Sie die Schulsachen?', '您都在哪裡買文具？',
   'parent', 'Meistens im Schreibwarenladen oder im Internet.', '通常在文具店或網路上。'],
  ['parent', 'parent', 'Geht Chris nach der Schule in die OGS?', 'Chris 放學後有去課後照顧（OGS）嗎？',
   'me', 'Ja, er bleibt bis 16 Uhr in der OGS.', '有，他在課後照顧待到下午 4 點。'],
  ['parent', 'me', 'Gibt es hier in der Nähe einen Spielplatz?', '這附近有遊樂場嗎？',
   'parent', 'Ja, im Park neben der Schule.', '有，在學校旁邊的公園裡。'],
  ['parent', 'parent', 'Wie gefällt es Chris in der Schule?', 'Chris 喜歡學校嗎？',
   'me', 'Sehr gut. Er geht gern zur Schule.', '很喜歡，他很喜歡上學。'],
  ['parent', 'me', 'Können Sie mir helfen? Ich verstehe diesen Zettel nicht.', '可以幫我一下嗎？這張紙條我看不懂。',
   'parent', 'Klar, zeigen Sie mal her.', '當然，給我看看。'],
  ['parent', 'parent', 'Holen Sie Chris jeden Tag ab?', '您每天都來接 Chris 嗎？',
   'me', 'Meistens ja. Manchmal holt ihn seine Oma ab.', '大部分是。有時候是他奶奶（外婆）來接。'],
  ['parent', 'me', 'Wollen wir zusammen zur Schule gehen?', '我們要不要一起走去學校？',
   'parent', 'Gute Idee! Treffen wir uns um halb acht an der Ecke?', '好主意！我們 7 點半在轉角碰面？'],
  ['parent', 'parent', 'Haben Sie am Wochenende etwas vor?', '您週末有什麼計畫嗎？',
   'me', 'Wir gehen vielleicht in den Zoo.', '我們可能會去動物園。'],
  ['parent', 'me', 'Ist morgen schulfrei?', '明天學校放假嗎？',
   'parent', 'Nein, morgen ist ganz normal Schule.', '沒有，明天照常上課。'],
  ['parent', 'parent', 'Kommen Sie am Freitag zum Schulfest?', '您星期五會來學校的園遊會嗎？',
   'me', 'Ja, gern. Soll ich einen Kuchen mitbringen?', '會，我要帶一個蛋糕去嗎？'],
  ['parent', 'me', 'Wie alt ist Ihr Sohn?', '您兒子幾歲？',
   'parent', 'Er ist sechs Jahre alt.', '他六歲。'],
  ['parent', 'parent', 'Wollen wir uns duzen?', '我們互相用「你（du）」來稱呼好嗎？',
   'me', 'Ja, gern! Das ist viel einfacher.', '好啊！這樣簡單多了。'],
  ['parent', 'me', 'Schönes Wochenende!', '週末愉快！',
   'parent', 'Danke, Ihnen auch!', '謝謝，您也是！'],

  // ---------------------------------------------------------------- 跟其他小朋友（du）
  ['kid', 'me', 'Hallo! Wie heißt du?', '哈囉！你叫什麼名字？',
   'kid', 'Ich heiße Lena.', '我叫 Lena。'],
  ['kid', 'me', 'Wie alt bist du?', '你幾歲？',
   'kid', 'Ich bin sechs Jahre alt.', '我六歲。'],
  ['kid', 'me', 'Bist du in der Klasse von Chris?', '你跟 Chris 同班嗎？',
   'kid', 'Ja, wir sitzen nebeneinander.', '對，我們坐在隔壁。'],
  ['kid', 'me', 'Möchtest du mit Chris spielen?', '你想跟 Chris 一起玩嗎？',
   'kid', 'Ja! Können wir Fangen spielen?', '想！我們可以玩鬼抓人嗎？'],
  ['kid', 'kid', 'Ist Chris heute da?', 'Chris 今天在嗎？',
   'me', 'Nein, er ist heute krank.', '不在，他今天生病了。'],
  ['kid', 'me', 'Hast du Hunger?', '你肚子餓嗎？',
   'kid', 'Ja, ich habe ein bisschen Hunger.', '嗯，我有一點餓。'],
  ['kid', 'me', 'Möchtest du etwas trinken?', '你想喝點東西嗎？',
   'kid', 'Ja, bitte. Ein Glas Wasser.', '好，麻煩給我一杯水。'],
  ['kid', 'me', 'Möchtest du einen Apfel oder eine Banane?', '你想吃蘋果還是香蕉？',
   'kid', 'Eine Banane, bitte.', '香蕉，謝謝。'],
  ['kid', 'kid', 'Darf ich mal auf die Toilette?', '我可以去上廁所嗎？',
   'me', 'Ja, klar. Die Toilette ist dort links.', '當然可以，廁所在那邊左手邊。'],
  ['kid', 'me', 'Was spielt ihr gern?', '你們喜歡玩什麼？',
   'kid', 'Wir spielen gern Fußball und Verstecken.', '我們喜歡踢足球和玩捉迷藏。'],
  ['kid', 'me', 'Wo wohnst du?', '你住在哪裡？',
   'kid', 'Ich wohne in der Nähe von der Schule.', '我住在學校附近。'],
  ['kid', 'kid', 'Kann Chris heute zu mir kommen?', 'Chris 今天可以來我家嗎？',
   'me', 'Heute nicht, aber vielleicht am Samstag.', '今天不行，不過星期六也許可以。'],
  ['kid', 'me', 'Holt dich deine Mama ab?', '你媽媽會來接你嗎？',
   'kid', 'Ja, sie kommt um drei.', '會，她三點來。'],
  ['kid', 'me', 'Hast du dir wehgetan?', '你受傷了嗎？',
   'kid', 'Ja, mein Knie tut weh.', '嗯，我的膝蓋好痛。'],
  ['kid', 'me', 'Was ist passiert?', '發生什麼事了？',
   'kid', 'Ich bin hingefallen.', '我跌倒了。'],
  ['kid', 'me', 'Brauchst du Hilfe?', '你需要幫忙嗎？',
   'kid', 'Ja, kannst du mir die Schuhe zubinden?', '要，你可以幫我綁鞋帶嗎？'],
  ['kid', 'me', 'Ist dir kalt?', '你會冷嗎？',
   'kid', 'Ja, mir ist kalt.', '會，我好冷。'],
  ['kid', 'me', 'Zieh bitte deine Jacke an.', '請把外套穿上。',
   'kid', 'Okay, mache ich.', '好，我穿。'],
  ['kid', 'me', 'Wir gehen jetzt nach Hause.', '我們現在要回家了。',
   'kid', 'Schade! Darf ich noch fünf Minuten spielen?', '可惜！我可以再玩五分鐘嗎？'],
  ['kid', 'me', 'Was ist dein Lieblingsessen?', '你最喜歡吃什麼？',
   'kid', 'Ich esse am liebsten Pizza.', '我最喜歡吃披薩。'],
  ['kid', 'me', 'Was ist deine Lieblingsfarbe?', '你最喜歡什麼顏色？',
   'kid', 'Meine Lieblingsfarbe ist Blau.', '我最喜歡藍色。'],
  ['kid', 'kid', 'Wo ist Chris?', 'Chris 在哪裡？',
   'me', 'Er ist draußen im Garten.', '他在外面的花園裡。'],
  ['kid', 'me', 'Habt ihr heute Hausaufgaben?', '你們今天有功課嗎？',
   'kid', 'Ja, wir müssen ein Blatt in Mathe machen.', '有，我們要寫一張數學學習單。'],
  ['kid', 'me', 'Wie war die Schule heute?', '今天在學校怎麼樣？',
   'kid', 'Gut! Wir haben ein Lied gesungen.', '很好！我們唱了一首歌。'],
  ['kid', 'kid', 'Darf ich mitspielen?', '我可以一起玩嗎？',
   'me', 'Ja, natürlich! Komm her.', '當然可以！過來吧。'],
  ['kid', 'me', 'Bitte nicht streiten. Ihr könnt euch abwechseln.', '請不要吵架，你們可以輪流。',
   'kid', 'Okay. Du zuerst, dann ich.', '好，你先，然後換我。'],
  ['kid', 'me', 'Vorsicht, die Straße!', '小心，有馬路！',
   'kid', 'Ich warte und schaue erst nach links und rechts.', '我會等，先看左邊再看右邊。'],
  ['kid', 'me', 'Danke für deine Hilfe!', '謝謝你的幫忙！',
   'kid', 'Bitte schön!', '不客氣！'],
  ['kid', 'me', 'Wann hast du Geburtstag?', '你什麼時候生日？',
   'kid', 'Im Mai. Dann werde ich sieben.', '五月。那時候我就七歲了。'],
  ['kid', 'me', 'Tschüss! Bis morgen!', '掰掰！明天見！',
   'kid', 'Tschüss! Bis morgen!', '掰掰！明天見！'],
].map(([scene, w1, de1, zh1, w2, de2, zh2], i, all) => {
  const n = all.slice(0, i + 1).filter(d => d[0] === scene).length;
  const id = `${scene[0]}${String(n).padStart(2, '0')}`;
  return { id, scene, lines: [{ who: w1, de: de1, zh: zh1 }, { who: w2, de: de2, zh: zh2 }] };
});
